kind: Service
apiVersion: v1
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
    version: v1
spec:
  selector:
    service: reverseproxy
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
