apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
    version: v1
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: pckhib/reverseproxy:ab
        name: reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
        ports:
          - containerPort: 8080
      restartPolicy: Always
